# Generated by Django 5.1.5 on 2025-04-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('scheduled_at', models.DateTimeField()),
                ('max_attempts', models.PositiveIntegerField()),
                ('allow_backtracking', models.BooleanField(default=False)),
                ('is_proctored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='exams.exam')),
                ('allow_negative_marking', models.BooleanField(default=False)),
                ('negative_mark_per_wrong', models.FloatField(default=0.0)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('allow_resume', models.BooleanField(default=False)),
                ('camera_required', models.BooleanField(default=False)),
            ],
        ),
    ]
